name: Release

on:
  push:



jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2


      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 10

      - name: Check for new verison
        id: version-check
        shell: bash
        run: |
          old_ver=$(git show ${{ github.sha }}^:package.json | jq -r '.version')
          new_ver=$(jq -r '.version' package.json)

          if [ "$old_ver" = "$new_ver" ]; then
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

          echo "new_ver=$new_ver" >> $GITHUB_OUTPUT

      - name: Skip if not updated
        if: steps.version-check.outputs.updated == 'false'
        run: |
          echo "No version change."
          exit 0

      - name: Package
        run: npm run package

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: SimpleMTC-${{ matrix.os }}=${{ steps.version-check.outputs.new_ver }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage