name: Release

on:
  push:



jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check for new verison
        id: version-check
        shell: bash
        run: |
          old_ver=$(git show ${{ github.sha }}^:package.json | jq -r '.version')
          new_ver=$(jq -r '.version' package.json)

          echo

          if [ "$old_ver" = "$new_ver" ]; then
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

          echo "new_ver=$new_ver" >> $GITHUB_OUTPUT

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest' && steps.version-check.outputs.updated == 'true'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev


      - name: Install node.js
        if: steps.version-check.outputs.updated == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Install dependencies
        if: steps.version-check.outputs.updated == 'true'
        run: npm ci
        timeout-minutes: 10

      - name: Package & Release
        if: steps.version-check.outputs.updated == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH: always
        run: npm run package